### ISSUE TITLE
Arrival must be after departure

### ISSUE THREAD

**Issue by atribe** [johanohly/AirTrail#31]
### The bug

**Arrival must be after departure** error showing up even though arrival time is after.

### Operating System that is running AirTrail

Linux

### AirTrail Version

v0.1.1

### Reproduction steps

1. Create new flight
2. set denver as from
3. set SLC as to
4. set departure and arrival date as the same day
5. set depature time to "12:40 PM"
6. set arrival time as "2:40 PM"
7. Click add flight

error pops up saying "Arrival must be after departure"

**Comment by johanohly** [comment]
Thank you for bringing this to my attention. You uncovered a bug related to how the application handles 12 PM times when converting from 12-hour to 24-hour format. Specifically, 12 PM was incorrectly being converted to 24:00 instead of 12:00, which caused the "Arrival must be after departure" error even when the arrival time was correctly after the departure time.

I have fixed this issue in the latest commit. The fix will be included in the next release. 
I appreciate your feedback and thank you for helping improve AirTrail!

**Comment by johanohly** [comment]
Fixed in v0.1.2
