### ISSUE TITLE
Incorrect flight durations on a number of flights (but not all)

### ISSUE THREAD

**Issue by adm-doss** [johanohly/AirTrail#55]
### The bug

Some of the determined flight durations are not being computed correctly.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/9218848a-2df1-4930-a551-ada224094042">

where the time should be approx 3:15 each way

<img width="731" alt="image" src="https://github.com/user-attachments/assets/863be942-13cd-4e54-a165-094e1d84a5f1">

... the time should be c. 3.30 each way

<img width="716" alt="image" src="https://github.com/user-attachments/assets/b6a5c2bd-8d88-42fe-bbe1-1aa0202152fb">

the time should be c. 9 hours

### Operating System that is running AirTrail

Linux

### AirTrail Version

latest

### Reproduction steps

1. Enter flight details in form
2. View entry in 'List flights'
3.
...

### Additional information

Johan - keep up the good work, - its appreciated.

**Comment by johanohly** [comment]
Thank you so much for taking the time to report this bug, and for your kind words—they mean a lot!

After investigating the examples you provided, I've identified that the root cause is related to Daylight Saving Time (DST). Currently, AirTrail uses a fixed UTC offset for each airport in its database, without accounting for whether a location observes DST. This approach leads to inconsistencies because:
1. Countries in the northern hemisphere observe DST during a different part of the year compared to countries in the southern hemisphere.
2. Approximately 60% of countries do not observe DST at all, which introduces additional edge cases that vary throughout the year.

As a result, flight durations may be calculated incorrectly in some cases. 

I do not currently know how to properly fix this, but one way to at least circumvent this issue for those affected, is to implement the ability to enter the departure and arrival time in the same time zone of your choice so AirTrail doesn't have to convert them both to the same time zone (the step where the issues arise). 

This feature has already been on my roadmap, but your report has certainly highlighted its importance. 

I appreciate your patience, and thank you again for your support!

**Comment by adm-doss** [comment]
Thanks, I can see that with the first two examples.  The third example (LHR~DEL) has a (possible) different/additional issue.  The duration should be c. 8.5 hours.  Possible DST and/or UTC offset of 4.5~5.5 hours and/or different start end dates (wild guesses).  Slightly unfair it falls to you to fix the worlds chronology issues.  ‘Date-fins’ any help, - v4.0 has time zone support (https://blog.date-fns.org/v40-with-time-zone-support/)  ??

**Comment by adm-doss** [comment]
Thanks, I can see that with the first two examples. The third example (LHR to DEL) has a (possible) different/additional issue. The duration should be c. 8.5 hours. Possible DST and/or UTC offset of 4.5 or 5.5 hours and/or different start end dates (wild guesses). Slightly unfair it falls to you to fix the worlds chronology issues. ‘Date-fins’ any help, - v4.0 has time zone support (https://blog.date-fns.org/v40-with-time-zone-support/) ??

**Comment by johanohly** [comment]
date-fns' new time zone module may actually be very helpful. I will definitely experiment with this, but it will probably be in two weeks time, when I get time.

**Comment by johanohly** [comment]
Currently testing #85 with your cases, and they all seem to work as expected now :)
![image](https://github.com/user-attachments/assets/abb294b1-d212-42db-93fe-91512876f01b)
