### ISSUE TITLE
[Bug Report] Incorrectly Displayed Border in Visited Countries

### ISSUE THREAD

**Issue by Walmarpole** [johanohly/AirTrail#82]
### The bug

Noticed when submitting unrelated visited countries feature request that the Gaza Strip displays as Israel in Visited countries but not in the default view. If this is intentional behavior for whatever reason, please lock issue accordingly. 

### Operating System that is running AirTrail

Unrelated

### AirTrail Version

v1.3.2

### Reproduction steps

1. Open AirTrail and move to Cyprus area
2. Switch to Visited countries to see difference

**Comment by johanohly** [comment]
This is for the same reason as the other missing countries on the visited countries map. The visited countries map renders the raw geometry of all the countries in the browser, so it has to make some sacrifices in detail (not made by me). 
The reason is that the visited countries feature is supposed to be pretty separate from the main map, and just supposed to be able to color countries, and be interactive.

For now the only path to actually seeing smaller countries on the globe is if someone who knows geojson, can modify the one I use to include them. Until then, marking those countries will only be possible through manual addition through a dedicated UI (#60).
